swagger: "2.0"
info:
  description: "This is a sample ExchangeCurrency server"
  title: "Currency Exchange Service"
  termsOfService: "WWW.EXC.MET"
  contact:
    email: "ignacio.galvez@accenture.com"
host: "http://localhost:8001"
basePath: "/v2"
tags:
- name: "exchange"
  description: "listing exchanges"
  name: "creation and deletion of currency exchanges"
  description: "Manipulation of currency exchanges"

schemes:
- "http"
paths:
    /currency-exchange/all:
        get:
            summary: "displays all existing currency exchanges available"
            tags:
            - "exchange"
            description: ""
            operationId: ""
            consumes:""
            produces:
            - "application/json"
            responses:
                "404":
            description: "not found"
  /currency-exchange/from/{from}/to/{to}:      
        get:
            summary: "display the currencyExchange value from currency from to currency to"
            tags:
            - "exchange"
            description: ""
            operationId: ""
            consumes:""
            produces:
            - "application/json"
            schema:
                $ref: "#/definitions/currencyExchange"
            responses:
                "404":
            description: "not found"
                "200":
                description: "Ok"
        post:
            tags:
            - "exchange"
            summary: "creates a new ExchangeCurrency"
            description: ""
            operationId: ""
            consumes:
            - "application/json"
            parameters:
            - in: "body"
            name: "body"
            description: "json object of the new currency exchange"
            required: true
            schema:
                $ref: "#/definitions/currency-exchange"
            responses:
                "500":
                description: " currencyExchange has been previosly created"
                "201":
                description: "created"
     
  